[workspace]
resolver = "2"
members = ["bw-aggr", "bw-api"]

[workspace.dependencies]
thiserror = "2.0.3"
reqwest = { version = "0.12.15", features = ["stream", "json", "gzip", "brotli", "deflate"] }
humantime = "2.1.0"
base64 = "0.22.1"
