apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: PBFA97CFB590B2093
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true

- name: Postgres
  type: postgres
  uid: P44368ADAD746BC27
  url: postgres:5432
  access: proxy
  editable: true
  user: ${PG_USERNAME}
  jsonData:
    database: ${PG_DATABASE}
    sslmode: disable
  secureJsonData:
    password: ${PG_PASSWORD}

- name: Loki
  type: loki
  uid: L4A7F8B9C2D1E3F5
  url: http://loki:3100
  access: proxy
  editable: true
  jsonData:
    maxLines: 5000
    derivedFields:
    - datasourceUid: PBFA97CFB590B2093
      matcherRegex: "trace_id=(\\w+)"
      name: TraceID
      url: "$${__value.raw}"

- name: "Axum"
  uid: "ferg6qzz72pdsa"
  orgId: 1
  type: "yesoreyeram-infinity-datasource"
  url: ${API_HOST}
  isDefault: false
  jsonData:
    httpHeaderName1: Authorization
    allowDangerousHTTPMethods: true
    global_queries: []
    allowedHosts:
    - ${API_HOST}
  secureJsonData:
    httpHeaderValue1: Bearer ${ADMIN_BEARER}
  readOnly: false
