global:
  scrape_interval: 15s
  evaluation_interval: 1m

rule_files:
- rules

scrape_configs:
- job_name: postgres
  static_configs:
  - targets: [ postgres:5432 ]

- job_name: prometheus
  static_configs:
  - targets: [ prometheus:9090 ]

- job_name: grafana
  static_configs:
  - targets: [ grafana:3000 ]

- job_name: node
  static_configs:
  - targets: [ exporter:9100 ]

# - job_name: loki
#   static_configs:
#   - targets: [ loki:3100 ]

# - job_name: api
#   static_configs:
#   - targets: [ api:5451 ]
